export const States = [
    "All States",
    "Kuala Lumpur",
    "Putrajaya",
    "Labuan",
    "Perlis",
    "Kedah",
    "Terengganu",
    "Pahang",
    "Perak",
    "Kelantan",
    "Pulau Pinang",
    "Selangor",
    "Negeri Sembilan",
    "Johor",
    "Melaka",
    "Sabah",
    "Sarawak",
]